# Example Test: StyleGAN2 with Superpixel Latent Conditioning (C2)
project_name: "GAN_Tests"
run_name: "stylegan2_sp_conditioned_c2_smoke_test"

dataset_path: "/path/to/your/image/dataset" # <<<<<< IMPORTANT: CHANGE THIS
cache_dir: "./cache_test_sg2_sp_cond" # Will create superpixel cache here
image_size: 64
num_superpixels: 30 # Fewer superpixels for faster precomputation/test
slic_compactness: 10.0

num_workers: 0
device: "cuda"
debug_num_images: 8
batch_size: 2
num_epochs: 1

model:
  architecture: "stylegan2"
  use_superpixel_conditioning: true # Enable superpixel processing

  # StyleGAN2 specific minimal params
  stylegan2_z_dim: 256 # Original Z dim
  stylegan2_w_dim: 256
  stylegan2_n_mlp: 4
  stylegan2_channel_multiplier: 1

  # Superpixel Conditioning (C2 Example - Latent Conditioning for Generator)
  stylegan2_g_latent_cond: true  # Enable C2 for StyleGAN2 Generator
  superpixel_latent_encoder_enabled: true # Ensure the global encoder switch is also on
  superpixel_feature_dim: 3 # RGB mean features
  superpixel_latent_encoder_hidden_dims: [64] # Small MLP for encoder
  superpixel_latent_embedding_dim: 128    # Output of SP encoder, will be concatenated to z_noise

  # Ensure ADA is off for this specific conditioning test to isolate effects
  stylegan2_ada_p_aug_initial: 0.0
  stylegan2_ada_interval_kimg: 0

optimizer:
  g_lr: 1e-4
  d_lr: 1e-4
  beta1: 0.0
  beta2: 0.99

logging:
  use_wandb: true
  wandb_entity: "YOUR_WANDB_ENTITY" # <<<<<< IMPORTANT: CHANGE THIS
  wandb_project_name: ${project_name}
  wandb_run_name: ${run_name}
  log_freq_step: 10
  sample_freq_epoch: 1
  num_samples_to_log: 4
  checkpoint_freq_epoch: 1

enable_fid_calculation: false
resume_checkpoint_path: null
output_dir_base: "experiment_outputs_tests"
