# Example Test: CycleGAN
project_name: "GAN_Tests"
run_name: "cyclegan_smoke_test"

dataset_path: "/path/to/your/domain_A/dataset" # <<<<<< IMPORTANT: CHANGE THIS (Domain A)
dataset_path_B: "/path/to/your/domain_B/dataset" # <<<<<< IMPORTANT: CHANGE THIS (Domain B)

cache_dir: "./cache_test_cyclegan" # CycleGAN doesn't use this cache type, but Trainer might expect it
image_size: 64
num_superpixels: 50 # Ignored
num_workers: 0
device: "cuda"
debug_num_images: 8 # Will apply to both domain A and B lists
batch_size: 2 # Small batch for test
num_epochs: 1

model:
  architecture: "cyclegan"
  # use_superpixel_conditioning: false # CycleGAN doesn't use this system by default

  # CycleGAN specific params
  cyclegan_input_nc: 3
  cyclegan_output_nc: 3
  cyclegan_ngf: 32 # Reduced for faster test
  cyclegan_ndf: 32 # Reduced for faster test
  cyclegan_n_blocks_gen: 3 # Fewer residual blocks
  cyclegan_n_layers_disc: 2 # Fewer discriminator layers
  cyclegan_lambda_cycle_a: 10.0
  cyclegan_lambda_cycle_b: 10.0
  cyclegan_lambda_identity: 0.5

optimizer:
  g_lr: 2.0e-4
  d_lr: 2.0e-4
  beta1: 0.5
  beta2: 0.999

logging:
  use_wandb: true
  wandb_entity: "YOUR_WANDB_ENTITY" # <<<<<< IMPORTANT: CHANGE THIS
  wandb_project_name: ${project_name}
  wandb_run_name: ${run_name}
  log_freq_step: 10
  sample_freq_epoch: 1
  num_samples_to_log: 4 # Will log fake_A, fake_B, rec_A, rec_B if trainer adapted for it, else just G_A2B samples
  checkpoint_freq_epoch: 1

enable_fid_calculation: false
resume_checkpoint_path: null
output_dir_base: "experiment_outputs_tests"
