# Example Test: StyleGAN2 Unconditioned (No ADA for this specific test)
project_name: "GAN_Tests"
run_name: "stylegan2_unconditioned_smoke_test"

dataset_path: "/home/student2/histo/data/lung_colon_image_set/lung_image_sets/lung_scc"
cache_dir: "./cache_test_sg2_uncond"
image_size: 64
num_superpixels: 50 # Ignored
num_workers: 0
device: "cuda"
debug_num_images: 8
batch_size: 2 # StyleGAN2 can be memory intensive
num_epochs: 1

model:
  architecture: "stylegan2"
  use_superpixel_conditioning: false

  # StyleGAN2 specific minimal params
  stylegan2_z_dim: 256
  stylegan2_w_dim: 256
  stylegan2_n_mlp: 4
  stylegan2_channel_multiplier: 1 # Keep low for small image_size

  # Ensure ADA is off for this specific unconditioned test
  stylegan2_ada_p_aug_initial: 0.0
  stylegan2_ada_interval_kimg: 0 # Effectively disables ADA updates

optimizer:
  g_lr: 1e-4
  d_lr: 1e-4
  beta1: 0.0
  beta2: 0.99

logging:
  use_wandb: true
  wandb_entity: "ciedaniel"
  wandb_project_name: ${project_name}
  wandb_run_name: ${run_name}
  log_freq_step: 10
  sample_freq_epoch: 1
  num_samples_to_log: 4
  checkpoint_freq_epoch: 1

enable_fid_calculation: false
resume_checkpoint_path: null
output_dir_base: "experiment_outputs_tests"
