# Example experiment_config.yaml for gan5_gcn architecture
# This file can be used to override defaults from BaseConfig.

# --- System and Paths ---
project_name: "SuperpixelGAN_LungSCC_Experiment1"
run_name: "stylegan2_unconditioned"
dataset_path: "/home/student2/histo/data/lung_colon_image_set/lung_image_sets/lung_scc/train"
dataset_path_val: "/home/student2/histo/data/lung_colon_image_set/lung_image_sets/lung_scc/val"
dataset_path_test: "/home/student2/histo/data/lung_colon_image_set/lung_image_sets/lung_scc/test"
# cache_dir: "custom_cache_location" # Override if needed
# output_dir_base: "/shared_drive/my_gan_experiments" # Override if needed

# --- Data and Preprocessing ---
image_size: 256
num_superpixels: 150
slic_compactness: 10.0
debug_num_images: 0 # Set to 0 to use all images for a proper experiment
num_workers: 4

# --- Model Configuration ---
model:
  architecture: "stylegan2"


  # Parameters for gan5_gcn architecture (will be ignored due to architecture switch)
  # g_channels: 128
  # g_num_gcn_blocks: 8
  # g_dropout_rate: 0.25
  # g_ada_in: False
  # g_spectral_norm: True
  # g_final_norm: "instancenorm"
  # d_channels: 64
  # d_spectral_norm: True

  # Parameters for gan6_gat_cnn architecture will primarily come from BaseConfig defaults
  # unless overridden here. For example:
  # gat_dim: 128 # Default from BaseConfig.ModelConfig
  # gan6_z_dim_graph_encoder_output: 128 # Default
  # gan6_z_dim_noise: 128 # Default
  # gan6_num_superpixels: 200 # Default, matches top-level num_superpixels

# --- Training Hyperparameters ---
batch_size: 8 # Reduced batch size from BaseConfig default
num_epochs: 250 # Increased epochs from BaseConfig default
optimizer:
  g_lr: 1e-5 # Lower generator learning rate
  d_lr: 1e-4 # Lower discriminator learning rate
  beta1: 0.0
  beta2: 0.99
r1_gamma: 5.0
d_updates_per_g_update: 2
gradient_accumulation_steps: 1 # Increase to trade computation for memory (effective_batch_size = batch_size * grad_accum_steps)

# --- Logging and Evaluation ---
logging:
  use_wandb: True
  wandb_project_name: "SuperpixelGAN_LungSCC_Experiment2" # Override if needed, else defaults to project_name
  wandb_run_name: "MyAmazingExperimentRun" # Override if needed, else defaults to run_name
  wandb_entity: "ciedaniel" # IMPORTANT: Set your W&B entity
  wandb_watch_freq_g: 1000 # Default, can override
  wandb_watch_freq_d: 1000 # Default, can override
  log_freq_step: 50
  sample_freq_epoch: 1
  num_samples_to_log: 8
  checkpoint_freq_epoch: 5

# FID calculation parameters remain top-level as per BaseConfig structure
enable_fid_calculation: True
fid_num_images: 50000
fid_batch_size: 32
fid_freq_epoch: 10 # Calculate FID less frequently

# --- Resume Training ---
# resume_checkpoint_path: null # or path/to/checkpoint.pth.tar