# WandB Sweep Configuration for gan6_gat_cnn

program: scripts/train.py # Path to your training script

method: bayes

metric:
  name: "val/FID_Score" # Or "val/Loss_G", "val/Loss_D_Adv" etc.
  goal: minimize

parameters:
  # --- Fixed parameters for this sweep series ---
  model.architecture:
    value: "gan6_gat_cnn"

  # For gan6_gat_cnn, superpixel processing is intrinsic to its ImageToGraphDataset.
  # The `model.use_superpixel_conditioning` flag is less relevant for its core mechanism.
  # Ablation of graph component is done via `model.gan6_gat_cnn_use_null_graph_embedding`
  # which can also be part of a sweep if desired.
  # model.gan6_gat_cnn_use_null_graph_embedding:
  #  values: [True, False]


  # --- Hyperparameters to Tune ---
  g_lr: # Learning rate for Generator (and Encoder in current gan6 setup)
    # Using specific values if log_uniform_values is problematic with legacy service
    values: [1e-6, 5e-6, 1e-5, 5e-5, 1e-4, 5e-4, 1e-3]

  d_lr: # Learning rate for Discriminator
    # Using specific values if log_uniform_values is problematic with legacy service
    values: [1e-6, 5e-6, 1e-5, 5e-5, 1e-4, 5e-4, 1e-3]


  r1_gamma:
    distribution: uniform
    min: 1.0
    max: 10.0

  # GAT Encoder parameters
  model.gat_dim:
    values: [64, 128, 256]
  model.gat_heads:
    values: [2, 4, 8]
  model.gat_layers:
    values: [2, 3, 4]
  # model.gat_dropout: # If implemented and used in GAT
  #   distribution: uniform
  #   min: 0.0
  #   max: 0.3

  model.gan6_z_dim_graph_encoder_output: # Output of GAT encoder
    values: [64, 128, 256]

  # CNN Generator parameters (conditioned on GAT output + noise)
  model.gan6_z_dim_noise: # Noise vector concatenated with graph embedding
    values: [64, 128, 256]
  # model.gan6_gen_init_size: # Usually fixed based on architecture, e.g., 4
  #   value: 4
  model.gan6_gen_feat_start: # Channels in the first layer of G_cnn
    values: [256, 512]

  # CNN Discriminator parameters
  model.gan6_d_feat_start: # Channels in the first layer of D_cnn
    values: [32, 64, 128]
  # model.gan6_d_final_conv_size: # Usually fixed, e.g., 16
  #   value: 16

  # Optional: Spectral norm toggles (if they make a big difference and are uncertain)
  # model.gan6_gen_spectral_norm:
  #   values: [True, False]
  # model.gan6_d_spectral_norm:
  #   values: [True, False]
  # model.gan6_d_spectral_norm_fc:
  #   values: [True, False]

# Command template for the agent to run
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config_file"
  - "configs/sweeps/base_for_sweeps.yaml" # Base settings for the sweep runs
  - ${args}
